import { z } from "zod";

export const ActivosFijosSchema = z.object({
  PropiedadesPlantasEquipos: z.object({
    Terrenos: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Edificios: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Maquinaria: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Buques: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Aeronave: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    EquiposTransporte: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    EnseresAccesorios: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    EquiposInformaticos: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    EquiposRedesComunicacion: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    InfraestructuraRed: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    ActivosTangiblesExploracionEvaluacion: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    ActivosMineria: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    ActivosPetroleoGas: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    PPyEArrendamientoOperativo: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    PlantasProductoras: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    AnimalesProductores: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    ConstruccionesProceso: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Otras: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Total: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
  }),
  PropiedadesInversión: z.object({
    Terrenos: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Edificios: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Total: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
  }),
  ANCMV: z.object({
    ANCMV: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
  }),
  TotalPPEPIANCMV: z.object({
    Contables: z.object({
      Comienzo: z.object({
        Costo: z.number(),
        Conversion: z.number(),
        Ajuste: z.number(),
      }),
      Incrementos: z.object({
        Transferencias: z.number(),
        CambiosValorRazonable: z.number(),
      }),
      Disminuciones: z.object({
        Transferencias: z.number(),
        CambiosValorRazonable: z.number(),
      }),
      Depreciacion: z.object({
        Costo: z.number(),
        Conversion: z.number(),
        Ajuste: z.number(),
      }),
      Deterioro: z.number(),
      ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
      GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
      GastoDetereorio: z.number(),
      IngresosPeriodoDetereorio: z.number(),
      ValorActivosLeasing: z.number(),
      DesmantelamientoRestauracion: z.number(),
      ValorRevaluacion: z.number(),
    }),
    Fiscales: z.object({
      SaldoComienzo: z.number(),
      IncrementosTransferencias: z.number(),
      DisminucionesTransferencias: z.number(),
      SubtotalFinalPeriodo: z.number(),
      Depreciacion: z.number(),
      TotalNeto: z.number(),
      GastoFiscalPeriodo: z.number(),
      ValorTotal: z.number(),
      DepreacionFinal: z.number(),
      ValorNeto: z.number(),
      GastoFiscal: z.number(),
    }),
  }),
  ActivosIntangibles: z.object({
    MarcasComerciales: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    ActivosIntangiblesExploracionEvaluacion: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    CabecerasOeriodicosRevistasTitulosPublicaciones: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    ProgramasAplicacionesInformaticos: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    LicenciasFranquicias: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    PropiedadIntelectualPatentesPropiedadIndustrialServiciosDerechosOperacion:
      z.object({
        Contables: z.object({
          Comienzo: z.object({
            Costo: z.number(),
            Conversion: z.number(),
            Ajuste: z.number(),
          }),
          Incrementos: z.object({
            Transferencias: z.number(),
            CambiosValorRazonable: z.number(),
          }),
          Disminuciones: z.object({
            Transferencias: z.number(),
            CambiosValorRazonable: z.number(),
          }),
          Depreciacion: z.object({
            Costo: z.number(),
            Conversion: z.number(),
            Ajuste: z.number(),
          }),
          Deterioro: z.number(),
          ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
          GastoDepreciacion: z.object({
            Costo: z.number(),
            Ajuste: z.number(),
          }),
          GastoDetereorio: z.number(),
          IngresosPeriodoDetereorio: z.number(),
          ValorActivosLeasing: z.number(),
          DesmantelamientoRestauracion: z.number(),
          ValorRevaluacion: z.number(),
        }),
        Fiscales: z.object({
          SaldoComienzo: z.number(),
          IncrementosTransferencias: z.number(),
          DisminucionesTransferencias: z.number(),
          SubtotalFinalPeriodo: z.number(),
          Depreciacion: z.number(),
          TotalNeto: z.number(),
          GastoFiscalPeriodo: z.number(),
          ValorTotal: z.number(),
          DepreacionFinal: z.number(),
          ValorNeto: z.number(),
          GastoFiscal: z.number(),
        }),
      }),
    RecetasFormulasModelosDiseñosPrototipos: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Concesiones: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    DesembolsosDesarrolloCapitalizados: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    ActivosIntangiblesDesarrollo: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Plusvalia: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    MejorasDerechosArrendamiento: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    SubvencionesEstado: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Otros: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
    Total: z.object({
      Contables: z.object({
        Comienzo: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Incrementos: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Disminuciones: z.object({
          Transferencias: z.number(),
          CambiosValorRazonable: z.number(),
        }),
        Depreciacion: z.object({
          Costo: z.number(),
          Conversion: z.number(),
          Ajuste: z.number(),
        }),
        Deterioro: z.number(),
        ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
        GastoDetereorio: z.number(),
        IngresosPeriodoDetereorio: z.number(),
        ValorActivosLeasing: z.number(),
        DesmantelamientoRestauracion: z.number(),
        ValorRevaluacion: z.number(),
      }),
      Fiscales: z.object({
        SaldoComienzo: z.number(),
        IncrementosTransferencias: z.number(),
        DisminucionesTransferencias: z.number(),
        SubtotalFinalPeriodo: z.number(),
        Depreciacion: z.number(),
        TotalNeto: z.number(),
        GastoFiscalPeriodo: z.number(),
        ValorTotal: z.number(),
        DepreacionFinal: z.number(),
        ValorNeto: z.number(),
        GastoFiscal: z.number(),
      }),
    }),
  }),
  TotalTodo: z.object({
    Contables: z.object({
      Comienzo: z.object({
        Costo: z.number(),
        Conversion: z.number(),
        Ajuste: z.number(),
      }),
      Incrementos: z.object({
        Transferencias: z.number(),
        CambiosValorRazonable: z.number(),
      }),
      Disminuciones: z.object({
        Transferencias: z.number(),
        CambiosValorRazonable: z.number(),
      }),
      Depreciacion: z.object({
        Costo: z.number(),
        Conversion: z.number(),
        Ajuste: z.number(),
      }),
      Deterioro: z.number(),
      ImporteNeto: z.object({ Costo: z.number(), Ajuste: z.number() }),
      GastoDepreciacion: z.object({ Costo: z.number(), Ajuste: z.number() }),
      GastoDetereorio: z.number(),
      IngresosPeriodoDetereorio: z.number(),
      ValorActivosLeasing: z.number(),
      DesmantelamientoRestauracion: z.number(),
      ValorRevaluacion: z.number(),
    }),
    Fiscales: z.object({
      SaldoComienzo: z.number(),
      IncrementosTransferencias: z.number(),
      DisminucionesTransferencias: z.number(),
      SubtotalFinalPeriodo: z.number(),
      Depreciacion: z.number(),
      TotalNeto: z.number(),
      GastoFiscalPeriodo: z.number(),
      ValorTotal: z.number(),
      DepreacionFinal: z.number(),
      ValorNeto: z.number(),
      GastoFiscal: z.number(),
    }),
  }),
});
