export const ActivosFijosInput = {
  PropiedadesPlantasEquipos: {
    Terrenos: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Edificios: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Maquinaria: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Buques: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Aeronave: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    EquiposTransporte: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    EnseresAccesorios: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    EquiposInformaticos: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    EquiposRedesComunicacion: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    InfraestructuraRed: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    ActivosTangiblesExploracionEvaluacion: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    ActivosMineria: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    ActivosPetroleoGas: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    PPyEArrendamientoOperativo: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    PlantasProductoras: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    AnimalesProductores: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    ConstruccionesProceso: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Otras: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Total: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
  },
  PropiedadesInversión: {
    Terrenos: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Edificios: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Total: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
  },
  ANCMV: {
    ANCMV: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
  },
  TotalPPEPIANCMV: {
    Contables: {
      Comienzo: {
        Costo: 0,
        Conversion: 0,
        Ajuste: 0,
      },
      Incrementos: {
        Transferencias: 0,
        CambiosValorRazonable: 0,
      },
      Disminuciones: {
        Transferencias: 0,
        CambiosValorRazonable: 0,
      },
      Depreciacion: {
        Costo: 0,
        Conversion: 0,
        Ajuste: 0,
      },
      Deterioro: 0,
      ImporteNeto: {
        Costo: 0,
        Ajuste: 0,
      },
      GastoDepreciacion: {
        Costo: 0,
        Ajuste: 0,
      },
      GastoDetereorio: 0,
      IngresosPeriodoDetereorio: 0,
      ValorActivosLeasing: 0,
      DesmantelamientoRestauracion: 0,
      ValorRevaluacion: 0,
    },
    Fiscales: {
      SaldoComienzo: 0,
      IncrementosTransferencias: 0,
      DisminucionesTransferencias: 0,
      SubtotalFinalPeriodo: 0,
      Depreciacion: 0,
      TotalNeto: 0,
      GastoFiscalPeriodo: 0,
      ValorTotal: 0,
      DepreacionFinal: 0,
      ValorNeto: 0,
      GastoFiscal: 0,
    },
  },
  ActivosIntangibles: {
    MarcasComerciales: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    ActivosIntangiblesExploracionEvaluacion: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    CabecerasOeriodicosRevistasTitulosPublicaciones: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    ProgramasAplicacionesInformaticos: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    LicenciasFranquicias: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    PropiedadIntelectualPatentesPropiedadIndustrialServiciosDerechosOperacion: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    RecetasFormulasModelosDiseñosPrototipos: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Concesiones: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    DesembolsosDesarrolloCapitalizados: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    ActivosIntangiblesDesarrollo: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Plusvalia: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    MejorasDerechosArrendamiento: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    SubvencionesEstado: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Otros: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
    Total: {
      Contables: {
        Comienzo: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Incrementos: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Disminuciones: {
          Transferencias: 0,
          CambiosValorRazonable: 0,
        },
        Depreciacion: {
          Costo: 0,
          Conversion: 0,
          Ajuste: 0,
        },
        Deterioro: 0,
        ImporteNeto: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDepreciacion: {
          Costo: 0,
          Ajuste: 0,
        },
        GastoDetereorio: 0,
        IngresosPeriodoDetereorio: 0,
        ValorActivosLeasing: 0,
        DesmantelamientoRestauracion: 0,
        ValorRevaluacion: 0,
      },
      Fiscales: {
        SaldoComienzo: 0,
        IncrementosTransferencias: 0,
        DisminucionesTransferencias: 0,
        SubtotalFinalPeriodo: 0,
        Depreciacion: 0,
        TotalNeto: 0,
        GastoFiscalPeriodo: 0,
        ValorTotal: 0,
        DepreacionFinal: 0,
        ValorNeto: 0,
        GastoFiscal: 0,
      },
    },
  },
  TotalTodo: {
    Contables: {
      Comienzo: {
        Costo: 0,
        Conversion: 0,
        Ajuste: 0,
      },
      Incrementos: {
        Transferencias: 0,
        CambiosValorRazonable: 0,
      },
      Disminuciones: {
        Transferencias: 0,
        CambiosValorRazonable: 0,
      },
      Depreciacion: {
        Costo: 0,
        Conversion: 0,
        Ajuste: 0,
      },
      Deterioro: 0,
      ImporteNeto: {
        Costo: 0,
        Ajuste: 0,
      },
      GastoDepreciacion: {
        Costo: 0,
        Ajuste: 0,
      },
      GastoDetereorio: 0,
      IngresosPeriodoDetereorio: 0,
      ValorActivosLeasing: 0,
      DesmantelamientoRestauracion: 0,
      ValorRevaluacion: 0,
    },
    Fiscales: {
      SaldoComienzo: 0,
      IncrementosTransferencias: 0,
      DisminucionesTransferencias: 0,
      SubtotalFinalPeriodo: 0,
      Depreciacion: 0,
      TotalNeto: 0,
      GastoFiscalPeriodo: 0,
      ValorTotal: 0,
      DepreacionFinal: 0,
      ValorNeto: 0,
      GastoFiscal: 0,
    },
  },
};