export const CaratulaInput = {
  "Año": 0,
  DatosDelDeclante: {
    NumeroDeIdentificacionTributariaNIT: 0,
    DV: 0,
    PrimerApellido: "",
    SegundoApellido: "",
    PrimerNombre: "",
    OtrosNombres: "",
    RazonSocial: "",
    CodigoDireccion: "",
  },
  Tarifas: {
    "Art240(Paragrafos1,2,4)": 0,
    Art2401ZonaFranca: 0,
    Art194240360: 0,
    MegainversionesHoteleras: 0,
    Megainversiones: 0,
    TarifGen: 0,
    Otra: 0
  },
  DatosInformativos: {
    PersonaNaturalSinResidencia: false,
    ContribuyenteDelRegimenTributarioEspecial: false,
    EntidadCooperativaArticulo19EstatutoTributario: false,
    EntidadDelSectorFinanciero: false,
    NuevaSociedadZOMAC: false,
    ObrasPorImpuestos: false,
    ProgramaDeReorganizacionEmpresarialDuranteElAñoGravable: false,
    SociedadExternaQuePrestaServicioDeTransporteEntreLugaresColombianosYExtranjeros: false,
    ObligadoAAplicarSistemasEspecialesDeCaloracionDeInversiones: false,
    CostoDeLosInventariosEstablecidosPorElSistemaDeJuegoDeInventarios: false,
    CostoDeLosInventariosEstablecidoSimultaneamentePorElJuegoDeInventariosYPorElSistemaDeJuegoDeInventarioPermanente: false,
    ProgresividadDeLaTaridaDeImpuestoDeRentaOSociedadExtranjeraOEntidadExtranjeraSinSucursalOEstablecimientoPermanente: false,
    ContratoDeEstabilidadJuridica: false,
    MonedaFuncionalDiferenteAlPesoColombiano: false,
    Megainversiones: false,
    EmpresaDeEconomíaNaranja: false,
    CompañiaHoldingColombiana: false,
    ZonaEconomicaYSocialEspecial: false,
  },
  NoIdentificacionSignatario: 0,
  CodigoRepresentacion: 0,
  CodigoContadorORevisorFiscal: 0,
  ConSalvedad: false,
  NumeroDeTarjetaProfesional: 0,
};