export const DetalleRenglonesInput = {
  R33: {
    510506: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    510527: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    510530: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    510533: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    510536: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    510539: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    510548: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520506: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520518: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520527: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520530: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520533: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520536: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520539: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520548: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720506: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720527: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720530: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720533: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720536: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720539: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720548: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R34: {
    510568: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    510569: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    510570: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520568: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520569: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520570: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720568: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720569: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720570: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R35: {
    510572: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    510575: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    510578: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520572: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520575: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    520578: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720572: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720575: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    720578: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R36: {
    1105: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1110: {
      Nac: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Ext: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    1115: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1120: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1125: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1140: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R37: {
    1205: {
      MedCost: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DetCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      MedValRazCamRes: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        EfectMed: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      MedValRazCamORI: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        EfectMed: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      MedMetPart: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        EfectApliPart: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DetCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    1210: {
      MedCost: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DetCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      MedValRazCamRes: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        EfectMed: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      MedValRazCamORI: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        EfectMed: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    1215: {
      InsFinDervNegMedCost: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DetCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      InsFinDervCovMedCost: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DetCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      DerFidNegMedCost: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DetCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    1216: {
      ValCost: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      DetCost: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R38: {
    1305: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1310: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1315: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1320: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1325: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1330: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1335: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1340: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1345: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1350: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1360: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1365: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1380: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1399: {
      DetCli: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      DetDem: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R39: {
    1405: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1410: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1415: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1430: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1435: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1440: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1455: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1460: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1465: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1499: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R40: {
    1505: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1507: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    "1510": {
      "REFSaldCont": 0,
      "Ajust1": 0,
      "Ajust2": "",
      "Ajust3": 0,
      "REFSaldFisc": 0
    },
    1520: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1558: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1569: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1570: {
      Plus: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Adq: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Fus: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Esci: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      CompAcc: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    1578: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1579: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R41: {
    1605: {
      AniProdCost: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DeprAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DetAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      AniProdCRaz: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Reval: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    1610: {
      AniConsCost: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DetAni: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      AniConsCRaz: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Reval: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    1615: {
      PlaProdCost: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DeprAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DetAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      PlaProdCRaz: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Reval: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    1620: {
      PlaConsCost: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DetAni: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      PlaConsCRaz: {
        ValCost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Reval: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R42: {
    1704: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1708: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1716: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1720: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1724: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1728: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1732: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1736: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1740: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1745: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1768: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    1769: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    "1779": {
      "ValCost": {
        "REFSaldCont": 0,
        "Ajust1": 0,
        "Ajust2": "",
        "Ajust3": 0,
        "SaldFisc": 0
      },
      "Reval": {
        "REFSaldCont": 0,
        "Ajust1": 0,
        "Ajust2": "",
        "Ajust3": 0,
        "SaldFisc": 0
      }
    },
    "1780": {
      "ValCost": {
        "REFSaldCont": 0,
        "Ajust1": 0,
        "Ajust2": "",
        "Ajust3": 0,
        "SaldFisc": 0
      },
      "Reval": {
        "REFSaldCont": 0,
        "Ajust1": 0,
        "Ajust2": "",
        "Ajust3": 0,
        "SaldFisc": 0
      }
    },
    "1788": {
      "ValCost": {
        "REFSaldCont": 0,
        "Ajust1": 0,
        "Ajust2": "",
        "Ajust3": 0,
        "SaldFisc": 0
      },
      "Reval": {
        "REFSaldCont": 0,
        "Ajust1": 0,
        "Ajust2": "",
        "Ajust3": 0,
        "SaldFisc": 0
      }
    },
    "1789": {
      "REFSaldCont": 0,
      "Ajust1": 0,
      "Ajust2": "",
      "Ajust3": 0,
      "SaldFisc": 0
    },
    "1790": {
      "ValCost": {
        "REFSaldCont": 0,
        "Ajust1": 0,
        "Ajust2": "",
        "Ajust3": 0,
        "REFSaldFisc": 0
      },
      "DeprAcum": {
        "REFSaldCont": 0,
        "Ajust1": 0,
        "Ajust2": "",
        "Ajust3": 0,
        "REFSaldFisc": 0
      },
      "Det": {
        "REFSaldCont": 0,
        "Ajust1": 0,
        "Ajust2": "",
        "Ajust3": 0,
        "SaldFisc": 0
      }
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R43: {
    1805: {
      AntiImpRenSobT: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      RetAutFuente: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      RetIVA: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      RetICA: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      SaldoFavor: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      SaldoIVA: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      SaldoICA: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    1810: {
      Plub: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PriSeg: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Arrend: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    1850: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    "1860": {
      "REFSaldCont": 0,
      "Ajust1": 0,
      "Ajust2": "",
      "Ajust3": 0,
      "SaldFisc": 0
    },
    CargDifInt: {
      ValCost: {
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AmortAcum: {
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R44: {
    TotCont: 0,
    TotFisc: 0,
  },
  R45: {
    2105: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2110: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2115: {
      Colombia: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      NoColombia: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    2205: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2210: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2335: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2355: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2365: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2367: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2368: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2370: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2404: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2408: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2412: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2505: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2510: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2515: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2525: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2530: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2605: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2705: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2710: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2715: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2805: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2810: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2815: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    "2816": {
      "REFSaldCont": 0,
      "Ajust1": 0,
      "Ajust2": "",
      "Ajust3": 0,
      "SaldFisc": 0
    },
    2820: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2825: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    "2826": {
      "REFSaldCont": 0,
      "Ajust1": 0,
      "Ajust2": "",
      "Ajust3": 0,
      "SaldFisc": 0
    },
    2835: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2840: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    2895: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    PasivRecFisc: {
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R46: {
    TotCont: 0,
    TotFisc: 0,
    3130: {
      SaldCont: 0,
    },
    3605: {
      UtilDesImp: {
        SaldCont: 0,
      },
      PerDesImp: {
        SaldCont: 0,
      },
    },
    3705: {
      SaldCont: 0,
    },
    3710: {
      SaldCont: 0,
    },
    3715: {
      GananAcum: {
        SaldCont: 0,
      },
      PerAcum: {
        SaldCont: 0,
      },
    },
    3720: {
      GananAcumORI: {
        SaldCont: 0,
      },
      PerAcumORI: {
        SaldCont: 0,
      },
    },
    3805: {
      Reval: {
        SaldCont: 0,
      },
      MetPar: {
        SaldCont: 0,
      },
    },
  },
  R47: {
    VentBien: {
      CliNac: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Export: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      CliZonFrac: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      SocCom: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      CliJuri: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      VincEcoZonFrac: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    ServGen: {
      CliNac: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Export: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      CliZonFrac: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      SocCom: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      CliJuri: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      VincEcoZonFrac: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    ServConst: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    AcuConcServ: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    ArrenOper: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    Regal: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    Comis: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    HonProf: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    ActSegCap: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    LibRes: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    ComBanc: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    Otro: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R48: {
    421005: {
      ArreFinMerc: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      IntFin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      IntPrest: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      IntFinAmrt: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      IntImplc: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    421020: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    421021: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    IntPresSoc: {
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R49: {
    RecSocNacMeg: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecSocNacNoMegNoSoc: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecSocNacNoMegSoc: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecSocNacSim: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  "R50": {
    "ValCont": 0,
    "ValFisc": 0
  },
  "R51": {
    "ValCont": 0,
    "ValFisc": 0,
    "Dat": {
      "SaldCont": 0,
      "Ajust1": 0,
      "Ajust2": "",
      "Ajust3": 0,
      "SaldFisc": 0
    }
  },
  R52: {
    RecSocNacMeg: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecSocNacNoMegNoSoc: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecSocNacNoMegSoc: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecSocNacSim: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R53: {
    RecSocNacNoMegNoSoc: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecSocNacNoMegSoc: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecSocNacSim: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R54: {
    RecSocNacNoMegNoSoc: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecSocNacNoMegSoc: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecSocNacSim: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  "R55": {
    "ValCont": 0,
    "ValFisc": 0
  },
  R56: {
    TotCont: 0,
    TotFisc: 0,
    RecSocNacMeg: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
  },
  R57: {
    4245: {
      Menos2: {
        PrpPlntEqp: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        PrpInv: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActBio: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActNoCorr: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActInta: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InvAccOtro: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DispInstr: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Otro: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      Mas2: {
        PrpPlntEqp: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        PrpInv: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActBio: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActNoCorr: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActInta: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InvAccOtro: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DispInstr: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Otro: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    4265: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    425035: {
      Inv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PrpPlntEqp: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActInt: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActExplrRecMat: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PrpInv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActNoCorrVent: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActBio: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      BienArtCult: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActFinan: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      CartCred: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      OtraInv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    425036: {
      Garan: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ContOner: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Litig: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Reembol: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Reestruc: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Pasiv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    425037: {
      BenefCortoPlz: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      BenefLargPlz: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      BenefEmplTemVinLab: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      BenefEmplPost: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    425050: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    4255: {
      ReembCompSeg: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    4295: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    429501: {
      GananApli: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      GananCamb: {
        InvAsoSubNegCon: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActBio: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        PropInv: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InstFinan: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InstDer: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Otro: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    429502: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    429503: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    429506: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    429507: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    429543: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R58: {
    TotCont: 0,
    TotFisc: 0,
  },
  R59: {
    TotCont: 0,
    TotFisc: 0,
    4175: {
      VentBien: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PresServ: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
  },
  R60: {
    DiviNoGrav: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    AprtObl: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    AprtVol: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    UtilEnaj: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    ValCap: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    Indem: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    Recom: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    Ganan: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    SubsAgro: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    TotFisc: 0,
  },
  R61: {
    TotCont: 0,
    TotFisc: 0,
  },
  R62: {
    61: {
      InvIniTrbProc: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      InvIniMatPri: {
        Data: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        CompLoc: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Imp: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InvFinMatPri: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      CostManoObr: {
        CortoPlz: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        LargoPlz: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        TermVincLab: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        PostEmpl: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      CostDepr: {
        DeprPrpPltEqu: {
          Cost: {
            SaldCont: 0,
            Ajust1: 0,
            Ajust2: "",
            Ajust3: 0,
            SaldFisc: 0,
          },
          AjusAcum: {
            SaldCont: 0,
            Ajust1: 0,
            Ajust2: "",
            Ajust3: 0,
            SaldFisc: 0,
          },
        },
        DeprPrpInv: {
          Cost: {
            SaldCont: 0,
            Ajust1: 0,
            Ajust2: "",
            Ajust3: 0,
            SaldFisc: 0,
          },
          AjusAcum: {
            SaldCont: 0,
            Ajust1: 0,
            Ajust2: "",
            Ajust3: 0,
            SaldFisc: 0,
          },
        },
        DeprActBio: {
          Cost: {
            SaldCont: 0,
            Ajust1: 0,
            Ajust2: "",
            Ajust3: 0,
            SaldFisc: 0,
          },
          AjusAcum: {
            SaldCont: 0,
            Ajust1: 0,
            Ajust2: "",
            Ajust3: 0,
            SaldFisc: 0,
          },
        },
        DepreActInt: {
          Cost: {
            SaldCont: 0,
            Ajust1: 0,
            Ajust2: "",
            Ajust3: 0,
            SaldFisc: 0,
          },
          AjusAcum: {
            SaldCont: 0,
            Ajust1: 0,
            Ajust2: "",
            Ajust3: 0,
            SaldFisc: 0,
          },
        },
        Otro: {
          Cost: {
            SaldCont: 0,
            Ajust1: 0,
            Ajust2: "",
            Ajust3: 0,
            SaldFisc: 0,
          },
          AjusAcum: {
            SaldCont: 0,
            Ajust1: 0,
            Ajust2: "",
            Ajust3: 0,
            SaldFisc: 0,
          },
        },
      },
      AmrtGatPagAnti: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Deterioros: {
        Inv: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        PrpPltEqu: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActInt: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActExp: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        PrpInver: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActNoCorr: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActBio: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        BienArt: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActFin: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        CartCred: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        OtrasInv: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DerUso: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Otros: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      Otros: {
        Arren: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Seguro: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Serv: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Honor: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      ServTecn: {
        VinEco: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        JurisNoCoop: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        NoVin: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      AsisTec: {
        VinEco: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        JurisNoCoop: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        NoVin: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Otros: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InvFinTrbProc: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InvIniProdTer: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        CostFabric: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InvFinProdTer: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      CostVentInv: {
        InvIni: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        CompLoc: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Import: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InvFin: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      CostVenSisPer: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    6140: {
      CostActRenExt: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      CostFiscActFij: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R63: {
    5105: {
      SalOtro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporEPS: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporARL: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporFondPen: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporSENA: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporICBF: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporCajaComp: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    5110: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5115: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5120: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5125: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5130: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5135: {
      ServAdmVinEco: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ServAdmVinTer: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ServAdmNoVin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ServTecVinEco: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ServTecVinTer: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ServTecNoVin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    5136: {
      VinEco: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      TerJurNoCoop: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      NoVin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    5137: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5140: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5145: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5150: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5155: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5160: {
      DeprePrpPltEqui: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      DeprePropInv: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      DepreOtro: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    5165: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5166: {
      AmortActInt: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      Otros: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    5195: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5199: {
      Inv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PrpPltEqui: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActInt: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActExplEva: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PropInv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActNoCorr: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      BienArt: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActBio: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActFin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      CartCred: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      OtroInv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      DerUso: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R64: {
    5205: {
      SalOtro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporEPS: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporARL: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporFondPen: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporSENA: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporICBF: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      AporCajaComp: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    5210: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5215: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    521501: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5220: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5225: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5230: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5235: {
      ServAdmVinEco: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ServAdmVinTer: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ServAdmNoVin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ServTecVinEco: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ServTecVinTer: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ServTecNoVin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    5236: {
      VinEco: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      TerJurNoCoop: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      NoVin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    5237: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5238: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5239: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5240: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5241: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5245: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5250: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5255: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5260: {
      DeprePrpPltEqui: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      DeprePropInv: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      DepreOtro: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      DepreActBio: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    5265: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5266: {
      AmortActInt: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      Otros: {
        Cost: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        AjusAcum: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    5295: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5299: {
      Inv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PrpPltEqui: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActInt: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActExplEva: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PropInv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActNoCorr: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      BienArt: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActBio: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActFin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      CartCred: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      OtroInv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      DerUso: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R65: {
    5305: {
      /**
       * ?se salto uno sotelo, ojo
       */
      IntDevSecFin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      IntDevPrestTer: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      InstFin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      CstTrans: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      DifCamb: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      IntImpl: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ActProvRecValPres: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      IntAccPref: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      IntDIANSegSoc: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R66: {
    5310: {
      Menos2: {
        PrpPltEqui: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        PrpInv: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActNoCor: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ValorVent: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DispOtroInst: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActInt: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InvAccPart: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Otro: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
      Mas2: {
        PrpPltEqui: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        PrpInv: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActNoCor: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ValorVent: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        DispOtroInst: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        ActInt: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        InvAccPart: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
        Otro: {
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      },
    },
    5313: {
      PerMetPart: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PerMedValRaz: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    5314: {
      ActBio: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PrpInv: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      InsFin: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      InsDer: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otros: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    5315: {
      Garant: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ContOne: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Litig: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ReembCli: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      ReestNeg: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      PasivCont: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    5316: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    5395: {
      TransBubAyuGub: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Don: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      Otro: {
        SaldCont: 0,
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      DeducEspcPubl: {
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
      DeducInvActFij: {
        Ajust1: 0,
        Ajust2: "",
        Ajust3: 0,
        SaldFisc: 0,
      },
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R67: {
    TotCont: 0,
    TotFisc: 0,
  },
  "R68": {
    "ValCont": 0,
    "ValFisc": 0
  },
  "R69": {
    "ValCont": 0,
    "ValFisc": 0
  },
  R70: {
    TotCont: 0,
    TotFisc: 0,
    IndmnCompAseg: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecCuen: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    RecDepre: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
  },
  "R71": {
    "ValCont": 0,
    "ValFisc": 0
  },
  R72: {
    TotCont: 0,
    TotFisc: 0,
  },
  R73: {
    TotCont: 0,
    TotFisc: 0,
  },
  "R74": {
    "CompenPerFisc": {
      "Val": 0
    },
    CompenExcRen: {
      Exc: 0,
      Sub: 0,
      ValFin: 0,
    },
    TotFisc: 0,
  },
  R75: {
    TotFisc: 0,
  },
  "R76": {
    "ValFisc": 0
  },
  R77: {
    Act235: 0,
    RentNet: 0,
    RentHot: 0,
    RentExent: 0,
    PensColom: 0,
    TotFisc: 0,
  },
  R78: {
    ActOmi: 0,
    PasivNoReal: 0,
    RecEsp: 0,
    RentComp: 0,
    RentLiq: 0,
    TotFisc: 0,
  },
  R79: {
    TotFisc: 0,
  },
  R80: {
    429543: {
      PreRifLot: {
        SaldCont: 0,
        Ajust1: 0,
        SaldFisc: 0,
      },
      PreVent: {
        SaldCont: 0,
        Ajust1: 0,
        SaldFisc: 0,
      },
      IngHerLeg: {
        SaldCont: 0,
        Ajust1: 0,
        SaldFisc: 0,
      },
      AprtSoc: {
        SaldCont: 0,
        Ajust1: 0,
        SaldFisc: 0,
      },
      GananOca: {
        SaldCont: 0,
        Ajust1: 0,
        SaldFisc: 0,
      },
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R81: {
    Valor: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R82: {
    Val: 0,
    TotFisc: 0,
  },
  R83: {
    CostFiscAct: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    Otros: {
      SaldCont: 0,
      Ajust1: 0,
      Ajust2: "",
      Ajust3: 0,
      SaldFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R84: {
    UtilVent: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    HerLegDon: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    Indemn: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    AprtSoc: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    TotFisc: 0,
  },
  R85: {
    Esc1: 0,
    Esc2: 0,
    Esc3: 0,
    Esc4: 0,
    TotFisc: 0,
  },
  R86: {
    TotFisc: 0,
  },
  R87: {
    TotFisc: 0,
  },
  "R88": {
    "ValFisc": 0
  },
  R89: {
    TotFisc: 0,
  },
  R90: {
    TotFisc: 0,
  },
  R91: {
    TotFisc: 0,
  },
  R92: {
    TotFisc: 0,
  },
  R93: {
    DescTrib: {
      Ajust1: 0,
      SaldFisc: 0,
    },
    DescDonEnt: {
      Donac: 0,
      PorcApli: 0,
      ValApli: 0,
      Limit: 0,
      Desc: 0,
    },
    Otro: {
      IndCom: 0,
      IVA: 0,
      RetTran: 0,
      Otro: 0,
    },
    TotFisc: 0,
  },
  R94: {
    TotFisc: 0,
  },
  "R95": {
    "LotRif": 0,
    "OtroGanOca": 0,
    "TotFisc": 0
  },
  "R96": {
    "ValFisc": 0
  },
  R97: {
    TotFisc: 0,
  },
  "R98": {
    "ValFisc": 0
  },
  "R99": {
    "ValFisc": 0
  },
  "R100": {
    "ValFisc": 0
  },
  "R101": {
    "ValFisc": 0
  },
  "R102": {
    "ValFisc": 0
  },
  "R103": {
    "ValCont": 0,
    "ValFisc": 0
  },
  R104: {
    Ventas: {
      Data: [
        {
          Nombre: "",
          Nit: "",
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      ],
      TotCont: 0,
      TotFisc: 0,
    },
    Servicio: {
      Data: [
        {
          Nombre: "",
          Nit: "",
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      ],
      TotCont: 0,
      TotFisc: 0,
    },
    HonorCom: {
      Data: [
        {
          Nombre: "",
          Nit: "",
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      ],
      TotCont: 0,
      TotFisc: 0,
    },
    RenFin: {
      Data: [
        {
          Nombre: "",
          Nit: "",
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      ],
      TotCont: 0,
      TotFisc: 0,
    },
    "DiviPart": {
      "Data": [
        {
          Nombre: "",
          Nit: "",
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      ],
      TotCont: 0,
      TotFisc: 0,
    },
    Otro: {
      Data: [
        {
          Nombre: "",
          Nit: "",
          SaldCont: 0,
          Ajust1: 0,
          Ajust2: "",
          Ajust3: 0,
          SaldFisc: 0,
        },
      ],
      TotCont: 0,
      TotFisc: 0,
    },
    TotCont: 0,
    TotFisc: 0,
  },
  R105: {
    TotFisc: 0,
  },
  "R106": {
    "ValFisc": 0
  },
  "R107": {
    "ValFisc": 0
  },
  "R108": {
    "ValFisc": 0
  },
  "R109": {
    "ValFisc": 0
  },
  R110: {
    TotFisc: 0,
  },
  R111: {
    Extem: 0,
    TotFisc: 0,
  },
  R112: {
    TotFisc: 0,
  },
  R113: {
    TotFisc: 0,
  },
  "R114": {
    "ValFisc": 0
  },
  "R115": {
    "ValFisc": 0
  }
};