export const ESFPatrimonioInput = {
  Activos: {
    ActivosEquivalentesEfectivo: {
      Efectivo: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      EquivalentesEfectivo: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      EfectivoRestringido: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    InversionesInstrumentosFinancierosDerivadosVN: {
      InversionesInstrumentosFinancierosDerivados: {
        DerechosRecompraInversiones: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        InversionesSubsidiariasAsociadasNegociosConjuntos: {
          ValorRazonableCambiosResultados: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          ValorRazonableCambiosORI: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          MetodoParticipacion: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          AlCosto: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          Total: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
        },
        InstrumentosDeudaCostoAmortizado: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        InstrumentosDeudaPatrimonioCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        InstrumentosDeudaPatrimonioValorRazonableResultados: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        InstrumentosDeudaPatrimonioValorRazonableORI: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        InstrumentosFinancierosDerivadosNegociación: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        InstrumentosFinancierosDerivadosCobertura: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DerechosFiduciarios: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Otros: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Total: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      DeterioroAcumuladoInversiones: {
        DerechosRecompraInversiones: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        InversionesSubsidiariasAsociadasNegociosConjuntos: {
          Metodo: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          Costo: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          Total: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
        },
        instrumentosDeudaCostoAmortizado: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        InstrumentosDeudaPatrimoniooCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DerechosFiduciarios: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Otros: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Total: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    CuentasComercialesCobrarOtrasPorCobrar: {
      CuentasDocumentosPorCobrar: {
        CarteraCreditoPrestamosBancarios: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CuentasComercialesPorCobrar: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CuentasPorCobrarAcuerdosConcesion: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        ArrendamientoFinancieroOLeasingFinanciero: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DividendosParticipaciones: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CuentasPorCobrarSociosAccionistasParticipes: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CuentasDocumentosPorCobrarOtrasPartesRelacionadasAsociadas: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        PrimasSegurosPorRecaudar: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CarteraDificilCobro: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        ReclamacionesPorCobrar: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        AnticiposPagos: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        OtrasCuentasDocumentosPorCobrar: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Total: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      DeterioroAcumuladoValorCuentasDocumentosCobrar: {
        CarteraDeCredito: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CuentasComercialesPorCobrar: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CuentasPorCobrarAcuerdosConcesion: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        ArrendamientoFinancieroLeasingFinanciero: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DividendosParticipaciones: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CuentasPorCobrarSociosAccionistasParticipes: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CuentasPorCobrarOtrasPartesRelacionadasAsociadas: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        OtrasCuentasPorCobrar: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Total: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    Inventarios: {
      ParaLaVentaNoProducidosPorLaEmpresa: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      EnTransito: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      MateriasPrimasSuministrosMateriales: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      EnProcesoDiferentesDeObrasInmueblesEnConstruccionParaVenta: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      CostosPrestadoresServicios: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      ProductoTerminadoDiferentesObrasInmueblesTerminadosParaVenta: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      ObrasInmueblesConstruccionParaVenta: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      ObrasInmueblesTerminadosParaVenta: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      PiezasRepuestoEquipoAuxiliarClasificadosComoInventarios: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      InventarioSurgeActividadExtraccion: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      DeterioroAcumuladoValorInventarios: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    GastosPagadosPorAnticipado: {
      Publicidad: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      PrimasSeguros: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Arrendamientos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Otros: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    ActivosImpuestosCorrientes: {
      SaldosaFavor: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      SaldosaFavorOtrosImpuestos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      DescuentosTributarios: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      AnticiposyOtros: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    ActivosImpuestosDiferidos: {
      ValorContable: 0,
      EfectoConversion: 0,
      MenorValorFiscal: 0,
    },
    PropiedadesPlantaEquipo: {
      Terrenos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      ConstruccionesEnProceso: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Edificios: {
        Costo: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        AjusteAcumuladoRevaluacionesReexpresiones: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      ActivosTangiblesExploracionEvaluacionRecursosMinerales: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      OtrasPropiedadesPlantaEquipo: {
        Costo: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        AjusteAcumuladoRevaluacionesReexpresiones: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Total: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      DepreciacionAcumuladaPropiedadesPlantaEquipo: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      DeterioroAcumuladoPropiedadesPlantaEquipo: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    ActivosIntangibles: {
      ActivosIntangiblesDistintosPlusvalia: {
        AcuerdosConcesionActivoIntangible: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        ActivosIntangiblesExploracionEvaluacionRecursosMinerales: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        MarcasPatentesLicenciasOtrosDerechos: {
          Costo: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          AjusteAcumuladoRevaluacionesReexpresiones: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          Total: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
        },
        ArrendamientoFinanciero: {
          Costo: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          AjusteAcumuladoRevaluacionesReexpresiones: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          Total: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
        },
        OtrosActivosIntangibles: {
          Costo: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          AjusteAcumuladoRevaluacionesReexpresiones: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          Total: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
        },
        AmortizacionAcumuladaActivosIntangiblesDistintosPlusvalia: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DeterioroAcumuladoActivosIntangiblesDistintosPlusvalia: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Total: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      PlusvaliaGoodwill: {
        PlusvaliaGoodwill: {
          AdquisicionEstablecimientoComercio: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          Fusiones: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          Escisiones: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          CompraAcciones: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
          Total: {
            ValorContable: 0,
            EfectoConversion: 0,
            MenorValorFiscal: 0,
            MayorValorFiscal: 0,
            ValorFiscal: 0,
          },
        },
        AmortizacionAcumuladaPlusvaliaGoodwill: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DeterioroAcumuladoPlusvaliaGoodwill: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Total: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    PropiedadesInversion: {
      TerrenoEdificios: {
        AlCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        AlValorRazonable: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      DepreciacionAcumuladaPropiedadesInversion: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      DeterioroAcumuladoPropiedadesInversion: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    ActivosNoCorrientes: {
      MantenidosParaVenta: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      DeterioroAcumuladoActivosCorrientesMantenidosParaVenta: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      MantenidosParaDistribuirPropietarios: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      DeterioroAcumuladoActivosCorrientesMantenidosParaDistribuirPropietarios: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    ActivosBiologicos: {
      AnimalesVivos: {
        AnimalesProductoresMedidosAlCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DepreciacionAcumuladaDeAnimalesProductoresMedidosAlCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DeterioroAcumuladoDeAnimalesProductoresMedidosAlCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        AnimalesProductoresMedidosAlValorRazonableMenosCostosDeVenta: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        AnimalesConsumiblesMedidosAlCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DeterioroAcumuladoAnimalesConsumiblesMedidosAlCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        AnimalesConsumiblesMedidosAlValorRazonableMenosCostosDeVenta: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Total: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      PlantasProductorasCultivosConsumibles: {
        PlantasProductorasMedidasAlCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DepreciacionAcumuladaDePlantasProductoras: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DeterioroAcumuladoDePlantasProductoras: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        PlantasProductorasMedidasAlValorRazonable: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CultivosConsumiblesMedidosAlCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        DeterioroAcumuladoCultivosConsumiblesMedidosAlCosto: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        CultivosConsumiblesMedidosAlValorRazonableMenosCostosDeVenta: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
        Total: {
          ValorContable: 0,
          EfectoConversion: 0,
          MenorValorFiscal: 0,
          MayorValorFiscal: 0,
          ValorFiscal: 0,
        },
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    OtrosActivos: {
      ActivosPlanBeneficiosEmpleados: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      OtrosActivos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      ActivosReconocidosSolamenteFinesFiscales: {
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    Total: {
      ValorContable: 0,
      EfectoConversion: 0,
      MenorValorFiscal: 0,
      MayorValorFiscal: 0,
      ValorFiscal: 0,
    },
  },
  Pasivos: {
    ObligacionesFinancierasCuentasPorPagar: {
      ObligacionesFinancierasEnMonedaLocal: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      ObligacionesFinancierasEnMonedaExtranjera: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      DepositosYExigibilidades: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      CuentasComercialesPorPagarEnMonedaLocal: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      CuentasComercialesPorPagarEnMonedaExtranjera: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      DividendosYParticipacionesPorPagar: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      CuentasPorPagarASociosAccionistasOParticipes: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      CuentasYDocumentosPorPagarAOtrasPartesRelacionadasYAsociadas: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      ReservaMatematicaYOTecnicaYOtrosPasivosExclusivosEnCompaniasDeSeguros: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      RecaudoAFavorDeTerceros: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      OtrasCuentasYDocumentosPorPagarEnMonedaLocal: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      OtrasCuentasYDocumentosPorPagarEnMonedaExtranjera: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    ArrendamientosPorPagar: {
      FinancieroLeasingPartesNoRelacionadas: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      FinancieroLeasingPartesRelacionadas: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Operativo: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    OtrosPasivosFinancieros: {
      BonosYDocumentosEquivalentes: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      InstrumentosFinancierosDerivados: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      AccionesPreferencialesOAportesDeCapitalClasificadosComoPasivos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      DerechosFiduciarios: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      OtrosPasivosFinancieros: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    ImpuestosGravamenesTasasPorPagar: {
      ImpuestoRenta: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      IVA: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Otrosimpuestos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    PasivosImpuestosDiferidos: {
      ValorContable: 0,
      EfectoConversion: 0,
      MenorValorFiscal: 0,
    },
    PasivosBeneficiosEmpleados: {
      CortoPlazo: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      LargoPlazo: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      TerminacionVinculosLaborales: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      PostEmpleo: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    Provisiones: {
      procesosLegalesLitigiosYDemandas: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      mantenimientoYReparaciones: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      obligacionesFiscales: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      desmantelamientosRestauracionYRehabilitacion: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      garantias: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      contratosOnerosos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      reembolsosAClientes: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      reestructuracionesDeNegocios: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      pasivosContingentesAsumidosEnUnaCombinacionDeNegocios: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      relacionadasConElMedioAmbiente: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      otrasProvisiones: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    PasivosIngresosDiferidos: {
      AnticiposYAvancesRecibidosDeClientes: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      IngresosDiferidosPorProgramasDeFidelizacion: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      SubvencionesDelGobiernoYOtrasAyudas: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      OtrosPasivosPorIngresosDiferidos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    OtrosPasivos: {
      DepositosRecibidos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      RetencionesATercerosSobreContratos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      EmbargosJudiciales: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      CuentasEnParticipacion: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      PasivoParaEjecucionDeExcedentesESAL: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      FondosSocialesMutualesYOtros: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      OtrosPasivos: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      PasivosReconocidosSolamenteParaFinesFiscales: {
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
        MenorValorFiscal: 0,
        MayorValorFiscal: 0,
        ValorFiscal: 0,
      },
    },
    Total: {
      ValorContable: 0,
      EfectoConversion: 0,
      MenorValorFiscal: 0,
      MayorValorFiscal: 0,
      ValorFiscal: 0,
    },
  },
  TotalPatrimonio: {
    ValorContable: 0,
    EfectoConversion: 0,
    MenorValorFiscal: 0,
    MayorValorFiscal: 0,
    ValorFiscal: 0,
  },
  PatrimonioContable: {
    CapitalSocialReservas: {
      CapitalPagado: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      AccionesCuotasPartesInteresSocialPropiasCartera: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      AportesSociales: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      CapitalAsignado: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      FondoSocialMutual: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      SuperavitCapital: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      Donaciones: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      ReservasLegalesEstatutarias: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      ReservasOcasionales: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      ReservasFondosEntidadesSolidarias: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      AsignacionesPermanentesRegimenTributarioEspecial: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      SuperavitRevaluaciones: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      SuperavitMetodoParticipacion: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      DividendosParticipacionesDecretadosAccionesCuotasPartesInteresSocial: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      SaldoCreditoInversionSuplementaria: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      SaldoDebitoInversionSuplementaria: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
    },
    ResultadoEjercicio: {
      UtilidadOExcedenteDelEjercicioEnOperacionesContinuadas: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      UtilidadOExcedenteDelEjercicioEnOperacionesDiscontinuadas: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      PerdidaODeficitDelEjercicioEnOperacionesContinuadas: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      PerdidaODeficitDelEjercicioEnOperacionesDiscontinuadas: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
    },
    ResultadosAcumulados: {
      UtilidadesOExcedentesAcumuladosSusceptiblesDeDistribucionATituloDeNoConstitutivoDeRentaNiGananciaOcasional:
        {
          ValorContable: 0,
          EfectoConversion: 0,
        },
      UtilidadesOExcedentesAcumuladosSusceptiblesDeDistribucionEnCalidadDeGravados:
        {
          ValorContable: 0,
          EfectoConversion: 0,
        },
      UtilidadesAcumuladasPorAjustesPorCorreccionDeErrores: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      UtilidadesPorAjustesPorCambiosEnPoliticasContables: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      PerdidasODeficitAcumulados: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      PerdidasAcumuladasPorAjustesPorCorreccionesDeErrores: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      PerdidasPorAjustesPorCambiosEnPoliticasContables: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
    },
    GananciasPerdidasAcumuladasRetenidasAdopcionPrimera: {
      GananciasPrimeraVez: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      PerdidasPrimeraVez: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
    },
    OtroResultadoIntegralAcumulado: {
      AjustePositivoPorEfectoConversion: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      AjusteNegativoPorEfectoConversion: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      GananciasAcomuladasORI: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      PerdidasAcumuladasORI: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      Total: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
    },
    Total: {
      ValorContable: 0,
      EfectoConversion: 0,
    },
  },
  DatosInformativos: {
    Activos: {
      TotalIntereses: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      TotalActivos: {
        ValorContable: 0,
        EfectoConversion: 0,
        ValorFiscal: 0,
      },
      InventariosTerceros: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      InventariosPoderTerceros: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
    },
    Pasivos: {
      TotalInteresespasivos: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      TotalPasivos: {
        ValorContable: 0,
        EfectoConversion: 0,
        ValorFiscal: 0,
      },
    },
    RetencionFuenteTrasladableArt2421ET: {
      ValorContable: 0,
      EfectoConversion: 0,
    },
    Patrimonio: {
      DividendosGravadosDecretadosPeriodo: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      DividendosNoGravadosDecretadosPeriodo: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      DividendosGravadosPagadosPeriodo: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      DividendosNoGravadosPagadosPeriodo: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
      DividendosGravadosPagadosPeriodoCargoUtilidades: {
        ValorContable: 0,
        EfectoConversion: 0,
      },
    },
  },
};