export const Form110Input = {
  DeclaracionDeRentaYComplementarioParaPersonasJuridicasYAsimiladas: {
    Año: 0,
    NumeroDeFormulario: 0,
    DatosDelDeclarante: {
      NIT: 0,
      DV: 0,
      PrimerApellido: "",
      SegundoApellido: "",
      PrimerNombre: "",
      OtrosNombres: "",
      RazonSocial: "",
      CodigoDireccionSeccional: "",
      ActividadEconomicaPrincipal: "",
      SiEsUnaCorrecionIndique: {
        Cod: 0,
        CodigoFormularioAnterior: 0,
      },
    },
    FraccionAñoGravableSiguiente: false,
    RenuncioAPertenecerAlRegimenTributarioEspecial: false,
    VinculadoAlPagoDeObrasPorImpuestos: false,
    PerdidasFiscalesAcumuladasAñosAnterioresSinCompensar: 0,
  },
  DatosResumen: {
    DatosInformativos: {
      TotalCostosGastosDeNomina: 0,
      AportesAlSistemaDeSeguridadSocial: 0,
      AportacionesSENAICBFCajasCompensacion: 0,
    },
    Patromonio: {
      EfectivoYEquivalentesDeEfectivo: 0,
      InversionesEInstrumentosFinancierosDerivados: 0,
      CuentasDocumentosYArrendamientosFinancierosPorCobrar: 0,
      Inventarios: 0,
      ActivosIntangibles: 0,
      ActivosBiologicos: 0,
      PropiedadesPlantaYEquipoPropiedadesDeInversionYANCMV: 0,
      OtrosActivos: 0,
      TotalPatrimonioBruto: 0,
      Pasivos: 0,
      TotalPatrimonioLiquido: 0,
    },
    Ingresos: {
      IngresosBrutosDeActividadesOrdinarias: 0,
      IngresosFinancieros: 0,
      DividendosYOParticipacionesNoConstitutivosDeRentaNiGananciaOcasional: 0,
      DividendosYOParticipacionesDistribuidasPorEntidadesNoResidentesEnColombiaAUnaCHC: 0,
      DividendosYOParticipacionesGravadas2016YAnterioresRecibidosPorSociedadesExtranjeras: 0,
      DividendosYOParticipacionesGravadas2016YAnterioresRecibidosPorPersonasNaturalesSinResidenciaFiscal: 0,
      DividendosYOParticipacionesGravadas2017YSiguientesRecibidosPorPersonasNaturalesSinResidenciaFiscal: 0,
      DividendosYOParticipacionesNoGravadasPeroQueTributaranAl10Porciento: 0,
      DividendosYOParticipacionesGravadas2017YSiguientesRecibidosPorEstablecimientosPermanentes: 0,
      DividendosYParticipacionesGravados2017YSiguientesRecibidosDeParteDeunasSociedadQueLlevoACaboMegainversiones: 0,
      OtrosIngresos: 0,
      TotalIngresosBrutos: 0,
      DevolucionesRebajasYDescuentosEnVentas: 0,
      IngresosNoConstitutivosDeRentaNiGananciaOcasional: 0,
      TotalIngresosNetos: 0,
    },
    CostosYDeducciones: {
      Costos: 0,
      GastosDeAdministracion: 0,
      GastosDeDistribucionYVentas: 0,
      GastosFinancieros: 0,
      OtrosGastosYDeducciones: 0,
      TotalCostosYGastosDeducibles: 0,
    },
    ESAL: {
      InversionesEfectuadasEnElAnio: 0,
      InversionesLiquidadasDePeriodosGravablesAnteriores: 0,
    },
    Renta: {
      RentaPorRecuperacionDeDeducciones: 0,
      RentaPasivaECESinResidenciaFiscalEnColombia: 0,
      RentaLiquidaOrdinariaDelEjercicioSinCasillas52A56: 0,
      OPerdidaLiquidaDelEjercicioSinCasillas52A56: 0,
      Compensaciones: 0,
      RentaLiquidaSinCasillas52A56: 0,
      RentaPresuntiva: 0,
      RentaExenta: 0,
      RentasGravables: 0,
      RentaLiquidaGravadaSinCasillas52A56: 0,
    },
    GananciasOcasionales: {
      IngresosParGananciasOcasionales: 0,
      RentasDeudoresRegimenLey1116De2006Decreto560YArt15Decreto772: 0,
      UtilizacionPerdidasFiscalesAcumuladasInciso2Articulo15Decreto772: 0,
      CostosPorGananciasOcasionales: 0,
      GananciasOcasionalesNoGravadasYExentas: 0,
      GananciasOcasionalesGravables: 0,
    },
    LiquidacionPrivada: {
      ImpuestosSobreLasRentasLiquidasGravables: {
        ImpuestoSobreLaRentaLiquidaGravableSinCasillas52A56: 0,
        DeDividendosYOParticipacionesGravadasALaTarifaDel10Porciento: 0,
        DeDividendosYOParticipacionesGravadasALaTarifaDelArticulo240DelET: 0,
        DeDividendosYOParticipacionesGravadasALaTarifaDel27Porciento: 0,
        DeDividendosYOParticipacionesGravadasALaTarifaDelArt240: 0,
        DeDividendosYOParticipacionesGravadasALaTarifaDel33Porciento: 0,
      },
      TotalImpuestoSobreLasRentasLiquidasGravables: 0,
      DescuentosTributarios: 0,
      ImpuestoNetoDeRenta: 0,
      ImpuestoDeGananciasOcasionales: 0,
      DescuentosPorImpuestosPagadosEnElExteriorPorGananciasOcasionales: 0,
      TotalImpuestoACargo: 0,
      MenosValorInversionObrasPorImpuestosHastaDelal50Porciento: 0,
      MenosDescuentoEfectivoInversionObrasPorImpuestos: 0,
      CreditoFiscalArticulo256: 0,
      MenosAnticipoRentaLiquidadoAnioGravableAnterior: 0,
      MenosSaldoAFavorAnioGravableAnteriorSinSolicitudDeDevolucion: 0,
      Retenciones: {
        Autorretenciones: 0,
        OtrasRetenciones: 0,
        TotalRetencionesAnioGravableADeclarar: 0,
      },
      MasAnticipoRentaParaElAnioGravableSiguiente: 0,
      SobretasaInstucionesFinancieras: {
        MenosAnticipoSobretasaInstitucionesFinancierasAnioGravableAnterior: 0,
        MasSobretasaInstitucionesFinancieras: 0,
        MasAnticipoSobretasaInstitucionesFinancierasAnioGravableSiguiente: 0,
      },
      SaldoAPagarPorImpuesto: 0,
      Sanciones: 0,
      TotalSaldoAPagar: 0,
      OTotalSaldoAFavor: 0,
    },
  },
  Totales: {
    ValorTotalImpuestoExigiblePorObrasPorImpuestosModalidadDePago1: 0,
    ValorTotalProyectoObrasPorImpuestosModalidadDePago2: 0,
    CodigoRepresentacion: 0,
    CodigoContratadorORevisorFiscal: 0,
    ConSalvedades: false,
    NumeroDeTarjetaProfesional: 0,
    PagoTotal: 0,
  },
};
