export const ImpuestoDiferidoInput = {
  ImpuestosDiferidosProvenientesDeDiferenciasTemporarias: {
    ActivoDiferidoDiferenciasTemporariasDeducibles: {
      EfectivoYEquivalentesAlEfectivo: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      InversionesEInstrumentosDerivados: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      CuentasPorCobrar: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      Inventarios: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      PropiedadesPlantaYEquipo: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      ActivosIntangibles: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      PropiedadesDeInversion: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      ActivosBiologicos: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      ActivosNoCorrientesMantenidosParaLaVentaEntregarAPropietarios: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      PasivosFinancierosYCuentasPorPagar: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      ImpuestosGravamenesYTasas: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      BeneficiosAEmpleados: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      Provisiones: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      OtrosPasivosAnticiposYAvancesRecibidos: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      OperacionesConTitulosYDerivados: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      PerdidasFiscalesYExcesosDeRentaPresuntiva: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      //TODO: cambiar nombre bien
      ActivosReconocidosSolamenteParaFinesFiscales: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      OtrosActivos: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      ValorTotal: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
    },
    PasivoDiferidoDiferenciasTemporariasImponibles: {
      EfectivoYEquivalentesAlEfectivo: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      InversionesEInstrumentosDerivados: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      CuentasPorCobrar: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      Inventarios: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      PropiedadesPlantaYEquipo: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      ActivosIntangibles: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      PropiedadesDeInversion: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      ActivosBiologicos: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      ActivosNoCorrientesMantenidosParaLaVentaEntregarAPropietarios: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      PasivosFinancierosYCuentasPorPagar: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      ImpuestosGravamenesYTasas: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      BeneficiosAEmpleados: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      Provisiones: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      OtrosPasivosAnticiposYAvancesRecibidos: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      OperacionesConTitulosYDerivados: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      PerdidasFiscalesYExcesosDeRentaPresuntiva: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      Fiscales: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      OtrosActivos: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
      ValorTotal: {
        BaseContable: 0,
        BaseFiscal: 0,
        DiferenciaTemporaria: 0,
        DiferenciaPermanente: 0,
        SaldoImpuestoDiferidoActual: 0,
        SaldoImpuestoDiferidoAnterior: 0,
        Variacion: 0,
        TasaFiscalAplicada: 0,
      },
    },
  },
  ActivosPorCreditosTributariosSaldosAfavorEImpuestosPagadosEnElEsterior: {
    SaldosAFavor: {
      Saldo31VigenciaActual: 0,
      Saldo31VigenciaAnterior: 0,
      Variacion: 0,
      ExplicacionDeLaVariacion: {
        ReduccionCompensacionApliacion: 0,
        CorreccionEnDeclaracionesAnterioresMayorValor: 0,
        CorreccionEnDeclaracionesAnterioresMenorValor: 0,
        AjustesContablesPorCorrecionesValorativasMayorValor: 0,
        AjustesContablesPorCorrecionesValorativasMenorValor: 0,
      },
    },
    ImpuestosPagadosEnELExterior: {
      Saldo31VigenciaActual: 0,
      Saldo31VigenciaAnterior: 0,
      Variacion: 0,
      ExplicacionDeLaVariacion: {
        ReduccionCompensacionApliacion: 0,
        CorreccionEnDeclaracionesAnterioresMayorValor: 0,
        CorreccionEnDeclaracionesAnterioresMenorValor: 0,
        AjustesContablesPorCorrecionesValorativasMayorValor: 0,
        AjustesContablesPorCorrecionesValorativasMenorValor: 0,
      },
    },
  },
  DetalleCompensacionPerdidasFiscales: {
    AñoAnterior: {
      Anio: 0,
      perdidasFiscalesAcumuladasPorCompensarAlInicioDelPeriodo: 0,
      PerdidaFiscalGeneradaEnElPeriodo: 0,
      PerdidaFiscalCompensadaEnElPeriodo: 0,
      ValoresNoCompensadosPorCaducidad: 0,
      AjustesPorCorreccionDeLaDeclaracionMayorValor: 0,
      AjustesPorCorreccionDeLaDeclaracionMenorValor: 0,
      PerdidaFiscalAcumuladaPorCompensarAlFinalDelPeriodo: 0,
      SaldoActivoPorImpuestoDiferidoAlFinalDelPeriodo: 0,
    },
    AñoActual: {
      Anio: 0,
      perdidasFiscalesAcumuladasPorCompensarAlInicioDelPeriodo: 0,
      PerdidaFiscalGeneradaEnElPeriodo: 0,
      PerdidaFiscalCompensadaEnElPeriodo: 0,
      ValoresNoCompensadosPorCaducidad: 0,
      AjustesPorCorreccionDeLaDeclaracionMayorValor: 0,
      AjustesPorCorreccionDeLaDeclaracionMenorValor: 0,
      PerdidaFiscalAcumuladaPorCompensarAlFinalDelPeriodo: 0,
      SaldoActivoPorImpuestoDiferidoAlFinalDelPeriodo: 0,
    },
  },
  DetalleDeLaCompensacionPorExcesoDeRentaPresuntiva: {
    AñoAnterior: {
      Anio: 0,
      ValorAcumuladoPorCompensarAlInicioDelPeriodo: 0,
      ValorGeneradoEnElPeriodo: 0,
      ValorCompensadoEnElPeriodo: 0,
      ValoresNoCompensadosPorCaducidad: 0,
      AjustesPorCorreccionDeLaDeclaracionMayorValor: 0,
      AjustesPorCorreccionDeLaDeclaracionMenorValor: 0,
      ValorAcumuladoPorCompensarAlFinalDelPeriodo: 0,
      SaldoActivoPorImpuestoDiferidoAlFinalDelPeriodo: 0,
    },
    AñoActual: {
      Anio: 0,
      ValorAcumuladoPorCompensarAlInicioDelPeriodo: 0,
      ValorGeneradoEnElPeriodo: 0,
      ValorCompensadoEnElPeriodo: 0,
      ValoresNoCompensadosPorCaducidad: 0,
      AjustesPorCorreccionDeLaDeclaracionMayorValor: 0,
      AjustesPorCorreccionDeLaDeclaracionMenorValor: 0,
      ValorAcumuladoPorCompensarAlFinalDelPeriodo: 0,
      SaldoActivoPorImpuestoDiferidoAlFinalDelPeriodo: 0,
    },
  },
};
