export * from "./ResumenEsfJson";
export * from "./IngFactJson";
export * from "./DetalleRenglonesJson";
export * from "./CaratulaJson"; 
export * from "./ActivosFijosJson";
export * from "./EsfPatrimonioJson";
export * from "./Form110Json";
export * from "./ImpuestoDiferidoJson";
export * from "./RentaLiquidaJson";
